// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POSManager.API.Invoices.Data;

#nullable disable

namespace POSManager.API.Invoices.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230522081737_AddInvocieTables")]
    partial class AddInvocieTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POSManager.API.Invoices.Models.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("GuestName");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("InvoiceNo");

                    b.Property<DateTime>("IssuedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smalldatetime")
                        .HasDefaultValue(new DateTime(2023, 5, 22, 16, 17, 37, 737, DateTimeKind.Local).AddTicks(1956))
                        .HasColumnName("IssuedDate");

                    b.Property<int?>("TableId")
                        .HasColumnType("int")
                        .HasColumnName("TableId");

                    b.HasKey("InvoiceId", "TenantId");

                    b.ToTable("Invoice", "dbo");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("POSManager.API.Invoices.Models.InvoiceItem", b =>
                {
                    b.Property<Guid>("InvoiceItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Description");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("InvoiceId");

                    b.Property<int>("LineNumber")
                        .HasColumnType("int")
                        .HasColumnName("LineNumber");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValue(0m)
                        .HasColumnName("Price");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductId");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Quantity");

                    b.HasKey("InvoiceItemId", "TenantId");

                    b.HasIndex("InvoiceId", "TenantId");

                    b.ToTable("InvoiceItem", "dbo");

                    b.HasAnnotation("Finbuckle:MultiTenant", true);
                });

            modelBuilder.Entity("POSManager.API.Invoices.Models.InvoiceItem", b =>
                {
                    b.HasOne("POSManager.API.Invoices.Models.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_InvoiceItem_Invoice");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("POSManager.API.Invoices.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");
                });
#pragma warning restore 612, 618
        }
    }
}
